

# 必填。随便找一个商品下单，然后进入结算页面，打开浏览器的调试窗口，切换到控制台Tab页，在控制台输入`eid`，获取eid。
eid   = "4EK4KUCMEU5EVC36VLZVO56WQW52BG6LYLOVPTOZJQMV2I424QTMNKRMDMYCCXY5DCXIYA7WMY7JVAH65H3UFQAQP4"

# 必填。随便找一个商品下单，然后进入结算页面，打开浏览器的调试窗口，切换到控制台Tab页，在控制台输入`fp`，获取eid。
fp    = "781d25834ea32a6c056bfc68a0d66424"

# 支付密码，可不填，待抢购成功，手动打开订单页面支付。
pwd   = ""

# 商品ID # 茅台ID "100012043978"
sku_id = "100012043978"
# 抢购数量
sku_num = "1"
